# Generated by Django 4.0.5 on 2022-08-21 07:16

from django.db import migrations


def create_default_user_and_user(apps, schema_migration):
    User = apps.get_model('authentication', 'User')
    Team = apps.get_model('authentication', 'Team')
    Permission = apps.get_model('auth', 'Permission')

    add_client = Permission.objects.get(codename='add_client')
    change_client = Permission.objects.get(codename='change_client')
    delete_client = Permission.objects.get(codename='delete_client')
    view_client = Permission.objects.get(codename='view_client')

    add_contract = Permission.objects.get(codename='add_contract')
    change_contract = Permission.objects.get(codename='change_contract')
    delete_contract = Permission.objects.get(codename='delete_contract')
    view_contract = Permission.objects.get(codename='view_contract')

    add_event = Permission.objects.get(codename='add_event')
    change_event = Permission.objects.get(codename='change_event')
    delete_event = Permission.objects.get(codename='delete_event')
    view_event = Permission.objects.get(codename='view_event')

    # create sales team and set permissions
    sales_permissions = [
        add_client,
        change_client,
        view_client,
        add_contract,
        change_contract,
        view_contract,
        add_event,
        view_event,
    ]
    sales_team = Team(name='Sales')
    sales_team.save()
    sales_team.permissions.set(sales_permissions)

    # create support team and set permissions
    support_permissions = [
        view_client,
        view_contract,
        change_event,
        view_event,
    ]
    support_team = Team(name='Support')
    support_team.save()
    support_team.permissions.set(support_permissions)

    # create management team and set permissions
    management_permissions = Permission.objects.all()
    management_team = Team(name='Management')
    management_team.save()
    management_team.permissions.set(management_permissions)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_user_and_user)
    ]
